services:
  - type: web
    name: duowatch
    env: node
    buildCommand: ./render-build.sh
    startCommand: node render-start.js
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
        - render-*.js
        - render-*.sh
    plan: free # Specify the plan (free or paid)
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: duowatch-db
          property: connectionString

databases:
  - name: duowatch-db
    plan: free
